/**
 * Behavioral tests for the quarantined USD adapter (SBAI-5433).
 *
 * Runs the REAL TinyUSDZ WASM engine against a self-contained .usdz fixture
 * generated by the app's own three.js (see ./gen-fixture.mjs — no third-party
 * asset enters the repo). Environment: default jsdom — the TinyUSDZ
 * emscripten glue is built web/worker-only, so it needs `window`, which also
 * matches the Tauri webview the adapter ships in.
 *
 * Two module seams are mocked, both limited to test-environment plumbing:
 *  - `tinyusdz/tinyusdz.js`: the real factory is still invoked, but with the
 *    WASM binary injected from disk (jsdom cannot fetch the package file).
 *  - `tinyusdz/tinyusdz.wasm?url`: satisfied with a placeholder; the binary
 *    above is what actually runs. In the app this resolves to the
 *    Vite-emitted asset URL.
 */
import { describe, expect, it, vi } from "vitest";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const wasmPath = join(here, "..", "..", "..", "node_modules", "tinyusdz", "tinyusdz.wasm");
const fixtureDir = join(here, "__fixtures__");

vi.mock("tinyusdz/tinyusdz.js", async (importOriginal) => {
  const real = await importOriginal<{
    default: (o?: object) => Promise<Record<string, unknown>>;
  }>();
  const wasmBinary = readFileSync(wasmPath);
  return {
    default: (options?: object) => real.default({ ...options, wasmBinary }),
  };
});
vi.mock("tinyusdz/tinyusdz.wasm?url", () => ({ default: "test-wasm-not-used" }));

// The emscripten glue asserts (inside its factory) that it is NOT running
// under Node ("node environment detected but not enabled at build time") —
// it is a web/worker-only build. Vitest always has `process.versions.node`
// set, so hide it for this file and restore afterwards. The Tauri webview
// (the real runtime) has no `process` global.
import { afterAll } from "vitest";
const nodeVersion = process.versions.node;
// @ts-expect-error -- deliberate temporary mutation for the web-only glue
delete process.versions.node;
afterAll(() => {
  process.versions.node = nodeVersion;
});

const { loadUsdToThree } = await import("./usdAdapter");

function fixtureDataUrl(name: string): string {
  const bytes = readFileSync(join(fixtureDir, name));
  return `data:application/octet-stream;base64,${bytes.toString("base64")}`;
}

function countMeshes(object: unknown): number {
  let count = 0;
  (object as { traverse: (cb: (c: unknown) => void) => void }).traverse((c) => {
    if ((c as { isMesh?: boolean }).isMesh) count += 1;
  });
  return count;
}

describe("usdAdapter (real TinyUSDZ WASM)", () => {
  it("parses a self-contained .usdz into renderable three.js geometry", async () => {
    const { object } = await loadUsdToThree(fixtureDataUrl("cube.usdz"));

    expect(object).toBeTruthy();
    // The fixture is a single cube mesh: the converted subtree must contain
    // real renderable geometry the viewer can frame.
    expect(countMeshes(object)).toBeGreaterThanOrEqual(1);
  }, 30_000);

  it("parses a bare .usda (no packaging) into renderable geometry", async () => {
    const { object } = await loadUsdToThree(fixtureDataUrl("cube.usda"));
    expect(countMeshes(object)).toBeGreaterThanOrEqual(1);
  }, 30_000);

  it("rejects garbage input with a real parse error, not a crash", async () => {
    const bogus = "data:text/plain;base64,bm90IGEgcmVhbCB1c2Q=";
    await expect(loadUsdToThree(bogus)).rejects.toThrow();
  }, 30_000);
});
